### ISSUE TITLE
How can I use my custom font?

### ISSUE THREAD

**Issue by trangtv04110** [wildbit/postmark-templates#10]
How can I use my custom font from an URL.
I added font-face to style tag at head tag, but it didn't work.
My template header like that:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <style type="text/css" rel="stylesheet" media="all">
    @font-face {
      font-family: PlusnetCreighton;
      src: url(https://s3-eu-west-1.amazonaws.com/assets.comparetechnology.co.uk/emails/plusnet/plusnetcreightonprobook.woff);
    }
    .plustnetFont {
      font-family: PlusnetCreighton,Arial,sans-serif;
    }
    /* Base ------------------------------ */

    *:not(br):not(tr):not(html) {
      font-family: PlusnetCreighton, Arial, 'Helvetica Neue', sans-serif;
      font-size: 16px;
      box-sizing: border-box;
    }

**Comment by trangtv04110** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <style type="text/css" rel="stylesheet" media="all">
    @font-face {
      font-family: PlusnetCreighton;
      src: url(https://s3-eu-west-1.amazonaws.com/assets.comparetechnology.co.uk/emails/plusnet/plusnetcreightonprobook.woff);
    }
    .plustnetFont {
      font-family: PlusnetCreighton,Arial,sans-serif;
    }
    /* Base ------------------------------ */

    *:not(br):not(tr):not(html) {
      font-family: PlusnetCreighton, Arial, 'Helvetica Neue', sans-serif;
      font-size: 16px;
      box-sizing: border-box;
    }

**Comment by trangtv04110** [comment]
why this issue was closed?

**Comment by mattmartincouk** [comment]
Quite possibly because this isn't a support forum.

**Comment by garrettdimon** [comment]
Yes, that's not an issue with the templates. That falls more into the realm of further customization. For these base templates, our primary goals are simplicity, ease of use, and compatibility. While we may dabble at custom external fonts in the future, it's not currently something that they're designed to support without heavy customization.
