### ISSUE TITLE
rendering mustachio in previews

### ISSUE THREAD

**Issue by ColeTMNZ** [wildbit/postmark-templates#13]
In trying to modify previews.html to render the mustachio template, I have failed to find a JS compatible library that can handle the sections appropriately. 

My reason for trying to do this, is my templates contain lots of conditional logic. 

I've seen suggested somewhere, to use handlebars to achieve what I desire, but handlebars dosn't support  the pathed sections. 

Any ideas on a library that might support?

**Comment by atheken** [comment]
Just curious, what's your ultimate goal for using the templates? 

Is it to use them with Postmark? If sending through Postmark, we have an editing tool that can do previews and validation within the web app.

It's totally cool if you're planning to use the templates within some other app/mail system, but if that's the case, what I would recommend is just making the small adjustments required to use either `mustache.js` or `handlebars` directly.

Handlebars does have pathing support, but the way it relative path scoping may be marginally different than how mustache behaves. [Search this page ](https://handlebarsjs.com/)for `../` for an example of how they do it.

**Comment by ColeTMNZ** [comment]
My intention is to use Previews as an instantaneous feedback loop when developing - however, with all the specific mustachio syntax for conditionals, my template is unreadable and not behaving close to expected. 

What I have ended up doing, is setting up a connect instance, and proxying a request to the postmark API +template/validate endpoint, which returns the rendered HTML (And accepts a model object. )

I considered using the postmark editor, but I miss my local dev tools too much  :-) 

Yes - I do intend to use with the Postmark service :-)

**Comment by atheken** [comment]
This comes up periodically, but it's not a super common request. It sounds like you've got the best approach already figured out.
