### ISSUE TITLE
Wrong Premailer linked to in readme?

### ISSUE THREAD

**Issue by caseyjhol** [wildbit/postmark-templates#14]
Based on the `-premailer-` prefixes in some of the CSS, it seems like you're wanting to recommend https://github.com/premailer/premailer instead of https://github.com/peterbe/premailer, or am I mistaken?

**Comment by derekrushforth** [comment]
Thanks for catching this @caseyjhol. You're right about that! I've updated the README so it links to the correct Premailer repo.
