### ISSUE TITLE
Text is not contrasted enough

### ISSUE THREAD

**Issue by Spone** [wildbit/postmark-templates#15]
In the templates, the text is not contrasted enough to pass [WCAG 2.0](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) level AAA or even AA requirements.
You could replace the text color with `#56595E` to fix the issue.

![image](https://user-images.githubusercontent.com/38524/52218914-e6478700-289b-11e9-8e50-6763cb1efe56.png)
using http://accessible-colors.com

**Comment by derekrushforth** [comment]
Thanks for reporting this @Spone. We [released some design improvements](https://github.com/wildbit/postmark-templates/releases/tag/v1.0.0) today and fixing the contrast was part of that.
