### ISSUE TITLE
Litmus tests returning 500 error

### ISSUE THREAD

**Issue by hbcondo** [wildbit/postmark-templates#16]
All the litmus test links on [readme.md](https://github.com/wildbit/postmark-templates/blob/master/README.md) are returning a 500 error:

https://litmus.com/pub/a087bdc
![image](https://user-images.githubusercontent.com/306958/54573277-ec577a00-49a8-11e9-8d29-838d9df84115.png)

**Comment by derekrushforth** [comment]
Thanks for reporting this @hbcondo. I've reached out to Litmus about seeing if we can create public links that don't expire. In the meantime, I've removed the Litmus test links from the README.

**Comment by kbond** [comment]
Any update on the litmus tests? I'm seeing some problems in a few clients and am trying to figure out if it is my email or does the default have the problem.

Could you perhaps publish the screenshots?
