### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by FabianKoestring** [wildbit/postmark-templates#19]
Hey there,

i´ve tried this email template but i cant get the dark mode to work. iOS13 supports dark mode but emails created with this template are not in dark mode.

**Comment by derekrushforth** [comment]
Hey @FabianKoestring,

I ran several of our templates through iOS13 in Litmus and dark mode seems to be working.
<img width="439" alt="Screen Shot 2019-11-14 at 11 18 26 AM" src="https://user-images.githubusercontent.com/3054417/68884505-8d313d00-06d0-11ea-831b-b27abdedabff.png">

Are you testing this using iOS13's default mail app? Which template are you using?

**Comment by FabianKoestring** [comment]
Sry, was my fault.
