### ISSUE TITLE
Darkmode doesn't work without meta tags

### ISSUE THREAD

**Issue by alyalin** [wildbit/postmark-templates#22]
Hi, thanks for awesome templates! But, I test on iOS and Mac OS default mail apps and dark mode doesn't work.
I added this to the template
```
 <meta name="color-scheme" content="light dark">
 <meta name="supported-color-schemes" content="light dark">
```

And this to style and this works as planned.

```
    :root {
      color-scheme: light dark;
      supported-color-schemes: light dark;
    }
```

What do you think?

**Comment by drpancake** [comment]
Thanks for this. It fixed dark mode in Superhuman.

**Comment by derekrushforth** [comment]
I confirmed that this fixed dark mode on both iOS and Mac OS mail apps using Litmus. The fix has been merged. Thanks for reporting this!
