### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by deepumi** [wildbit/postmark-templates#6]
Hi,

How do I add social media icons on the footer section?. 

Any samples available?

Thank you
Deepu

**Comment by derekrushforth** [comment]
Hey @deepumi,

We don't have any examples of social media icons in this repo, sorry about that. 

I suggest that you check out [MailMason](https://github.com/wildbit/mailmason). It's a workflow we built using [gruntJS](https://gruntjs.com/) and we use it to generate the templates in this repo. MailMason lets you include [social media icons](https://github.com/wildbit/mailmason/wiki/Getting-Started#social-images) as well as a bunch of other options to fully customize your templates. Hope that helps!

**Comment by deepumi** [comment]
@derekrushforth Thanks, I have looked at MailMason before posting the issue. However, just to add a social media icons, I don't want to install node and other tools + config json files.

Since the template already support some social media css, It would be great if you can implement it in the template itself.

**Comment by derekrushforth** [comment]
Gotcha. For now, the only way to do this is through MailMason. We'll keep this in mind as we make improvements.

If you'd like, you can add the icons to your templates manually. Here's everything you need:

- [HTML](https://github.com/wildbit/mailmason/blob/master/src/partials/footer.hbs#L3)(You'll need to exclude the handlebars logic)
- [CSS](https://github.com/wildbit/mailmason/blob/master/src/stylesheets/scss/_layout.scss#L137)
- [Images](https://github.com/wildbit/mailmason/tree/master/src/images)

**Comment by deepumi** [comment]
@derekrushforth 
Thank you.. Looking forward to see the implementation!
