### ISSUE TITLE
iOS Mail Reader and iCloud Mail

### ISSUE THREAD

**Issue by AdamTylerLynch** [wildbit/postmark-templates#7]
The template within inline CSS is not rendering correctly on iOS mail (it's small) and on iCloud mail its really wide and causes scrolling.

**Comment by AdamTylerLynch** [comment]
Sample Image: https://snag.gy/LQHt1r.jpg

**Comment by AdamTylerLynch** [comment]
HTML code: https://pastebin.com/CiyZUTWv

**Comment by derekrushforth** [comment]
Hey @AdamTylerLynch,

Thanks for reporting this! Looks like the layout breaks when the plain text URL near the footer is longer than the content width. I added some CSS which should do the fix. You can grab the code from the commit above, or add this CSS property to line 93 of your [template](https://pastebin.com/CiyZUTWv):

Add `word-break: break-word;`
```
<td class="content-cell" align="center" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding: 35px; word-break: break-word;">
```

Give that a shot and let me know if it works.
