### ISSUE TITLE
Fail: Litmus test results →

### ISSUE THREAD

**Issue by AndreSchwarzer** [wildbit/postmark-templates#8]
Hi,

none of the `Litmus test results →` links shows renderings of the emails.

![screen shot 2017-04-21 at 13 38 23](https://cloud.githubusercontent.com/assets/6991100/25275888/d452b752-2697-11e7-8077-2d7640cd60e7.png)

**Comment by derekrushforth** [comment]
Thanks for the heads up @AndreSchwarzer. We'll get this fixed.

**Comment by v-karbovnichy** [comment]
And now all Litmus test result links are 404

![image](https://user-images.githubusercontent.com/7301634/35264977-25285bbc-0038-11e8-9ef3-0aedd66a4b69.png)

**Comment by derekrushforth** [comment]
Thanks folks. The Litmus links are fixed now.
